package com.zuovx.Model;

import java.io.Serializable;

public class Doctor implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.doctor_id
     *
     * @mbggenerated
     */
    private Integer doctorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.sex
     *
     * @mbggenerated
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.age
     *
     * @mbggenerated
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.account
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.introduction
     *
     * @mbggenerated
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.forte
     *
     * @mbggenerated
     */
    private String forte;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.id_number
     *
     * @mbggenerated
     */
    private String idNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.section_id
     *
     * @mbggenerated
     */
    private Integer sectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.honour
     *
     * @mbggenerated
     */
    private String honour;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.doctor_id
     *
     * @return the value of doctor.doctor_id
     *
     * @mbggenerated
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.doctor_id
     *
     * @param doctorId the value for doctor.doctor_id
     *
     * @mbggenerated
     */
    @Override
    public String toString(){
        return name;
    }
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.name
     *
     * @return the value of doctor.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.name
     *
     * @param name the value for doctor.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.sex
     *
     * @return the value of doctor.sex
     *
     * @mbggenerated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.sex
     *
     * @param sex the value for doctor.sex
     *
     * @mbggenerated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.age
     *
     * @return the value of doctor.age
     *
     * @mbggenerated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.age
     *
     * @param age the value for doctor.age
     *
     * @mbggenerated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.account
     *
     * @return the value of doctor.account
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.account
     *
     * @param account the value for doctor.account
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.phone
     *
     * @return the value of doctor.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.phone
     *
     * @param phone the value for doctor.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.introduction
     *
     * @return the value of doctor.introduction
     *
     * @mbggenerated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.introduction
     *
     * @param introduction the value for doctor.introduction
     *
     * @mbggenerated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.forte
     *
     * @return the value of doctor.forte
     *
     * @mbggenerated
     */
    public String getForte() {
        return forte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.forte
     *
     * @param forte the value for doctor.forte
     *
     * @mbggenerated
     */
    public void setForte(String forte) {
        this.forte = forte == null ? null : forte.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.id_number
     *
     * @return the value of doctor.id_number
     *
     * @mbggenerated
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.id_number
     *
     * @param idNumber the value for doctor.id_number
     *
     * @mbggenerated
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.section_id
     *
     * @return the value of doctor.section_id
     *
     * @mbggenerated
     */
    public Integer getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.section_id
     *
     * @param sectionId the value for doctor.section_id
     *
     * @mbggenerated
     */
    public void setSectionId(Integer sectionId) {
        this.sectionId = sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.honour
     *
     * @return the value of doctor.honour
     *
     * @mbggenerated
     */
    public String getHonour() {
        return honour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.honour
     *
     * @param honour the value for doctor.honour
     *
     * @mbggenerated
     */
    public void setHonour(String honour) {
        this.honour = honour == null ? null : honour.trim();
    }
}