package com.zuovx.Model;

import java.io.Serializable;

public class ScheduleT implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.schedule_id
     *
     * @mbggenerated
     */
    private Integer scheduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.doctor_id
     *
     * @mbggenerated
     */
    private Integer doctorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.w
     *
     * @mbggenerated
     */
    private Integer w;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.remainder
     *
     * @mbggenerated
     */
    private Integer remainder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.work_time_start
     *
     * @mbggenerated
     */
    private long workTimeStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.is_cancle
     *
     * @mbggenerated
     */
    private Boolean isCancle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.schedule_id
     *
     * @return the value of schedule.schedule_id
     *
     * @mbggenerated
     */
    public Integer getScheduleId() {
        return scheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.schedule_id
     *
     * @param scheduleId the value for schedule.schedule_id
     *
     * @mbggenerated
     */
    public void setScheduleId(Integer scheduleId) {
        this.scheduleId = scheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.doctor_id
     *
     * @return the value of schedule.doctor_id
     *
     * @mbggenerated
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.doctor_id
     *
     * @param doctorId the value for schedule.doctor_id
     *
     * @mbggenerated
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.w
     *
     * @return the value of schedule.w
     *
     * @mbggenerated
     */
    public Integer getW() {
        return w;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.w
     *
     * @param w the value for schedule.w
     *
     * @mbggenerated
     */
    public void setW(Integer w) {
        this.w = w;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.remainder
     *
     * @return the value of schedule.remainder
     *
     * @mbggenerated
     */
    public Integer getRemainder() {
        return remainder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.remainder
     *
     * @param remainder the value for schedule.remainder
     *
     * @mbggenerated
     */
    public void setRemainder(Integer remainder) {
        this.remainder = remainder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.work_time_start
     *
     * @return the value of schedule.work_time_start
     *
     * @mbggenerated
     */
    public long getWorkTimeStart() {
        return workTimeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.work_time_start
     *
     * @param workTimeStart the value for schedule.work_time_start
     *
     * @mbggenerated
     */
    public void setWorkTimeStart(long workTimeStart) {
        this.workTimeStart = workTimeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.is_cancle
     *
     * @return the value of schedule.is_cancle
     *
     * @mbggenerated
     */
    public Boolean getIsCancle() {
        return isCancle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.is_cancle
     *
     * @param isCancle the value for schedule.is_cancle
     *
     * @mbggenerated
     */
    public void setIsCancle(Boolean isCancle) {
        this.isCancle = isCancle;
    }
}